app:
  name: "zim.task"
logger:
    level: "debug"
    filename: "logs/task.log"
    maxSize: 100
    maxBackups: 10
    maxAge: 7
    compress: true
registry:
  basePath: "/zmicro"
  updateInterval: 30
  etcdAddr:
    - "etcd:2379"
mysql:
  dataSource: "root:123456@tcp(mysql:3306)/zim?charset=utf8mb4&parseTime=true&loc=Local"
  maxIdle: 10
  maxOpen: 100
redis:
  addr: "redis:6379"
  password: "123456"
  db: 1
nats:
  addr: "nats://nats:4222"
