version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    command: mysqld --sql_mode=
    ports:
      - 3306:3306
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - /data/zim/mysql:/var/lib/mysql

  redis:
    image: redis:6.2.6
    container_name: redis
    restart: always
    command: redis-server --requirepass 123456 --appendonly yes
    ports:
      - 6379:6379
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /data/zim/redis:/data

  etcd:
    image: quay.io/coreos/etcd:latest
    container_name: etcd
    restart: always
    ports:
      - "2379:2379"
    volumes:
      - /data/zim/etcd:/etcd-data
    command: etcd --data-dir=/etcd-data --name node1 --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://0.0.0.0:2379

#  etcd:
#    image: bitnami/etcd:3.5
#    container_name: etcd
#    restart: always
##    command: etcd --name node1 --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://0.0.0.0:2379
#    ports:
#      - 2379:2379
#      - 2380:2380
#    volumes:
#      - /data/etcd:/bitnami/etcd
#    environment:
#      - ALLOW_NONE_AUTHENTICATION=yes
#      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379

  nats:
    image: nats:2.8.2
    container_name: nats
    restart: always
    command: -js
    ports:
      - 4222:4222
      - 8222:8222
    volumes:
      - /data/zim/nats/jetstream:/tmp/nats/jetstream
    environment:
      - TZ=Asia/Shanghai

  zim-all-in-one:
    image: iobrother/zim-all-in-one:latest
    container_name: zim-all-in-one
    restart: always
    ports:
      - "2001:2001"
      - "5080:5080"
      - "5188:5188"
    volumes:
      - /data/zim/logs:/logs
    depends_on:
      - redis
      - mysql
      - nats
      - etcd



