// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/rest/chat/chat.proto

package chat

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendReq struct {
	ConvType int32  `protobuf:"varint,1,opt,name=conv_type,json=convType,proto3" json:"conv_type,omitempty"`
	MsgType  int32  `protobuf:"varint,2,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	Sender   string `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	Target   string `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	Content  string `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *SendReq) Reset()         { *m = SendReq{} }
func (m *SendReq) String() string { return proto.CompactTextString(m) }
func (*SendReq) ProtoMessage()    {}
func (*SendReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac80e97576f6ff81, []int{0}
}
func (m *SendReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SendReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SendReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SendReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendReq.Merge(m, src)
}
func (m *SendReq) XXX_Size() int {
	return m.Size()
}
func (m *SendReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendReq proto.InternalMessageInfo

func (*SendReq) XXX_MessageName() string {
	return "github.com.zchat.team.zim.api.rest.chat.SendReq"
}

type SendRsp struct {
	Id       int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SendTime int64 `protobuf:"varint,2,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
}

func (m *SendRsp) Reset()         { *m = SendRsp{} }
func (m *SendRsp) String() string { return proto.CompactTextString(m) }
func (*SendRsp) ProtoMessage()    {}
func (*SendRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac80e97576f6ff81, []int{1}
}
func (m *SendRsp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SendRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SendRsp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SendRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendRsp.Merge(m, src)
}
func (m *SendRsp) XXX_Size() int {
	return m.Size()
}
func (m *SendRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SendRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SendRsp proto.InternalMessageInfo

func (*SendRsp) XXX_MessageName() string {
	return "github.com.zchat.team.zim.api.rest.chat.SendRsp"
}
func init() {
	proto.RegisterType((*SendReq)(nil), "github.com.zchat.team.zim.api.rest.chat.SendReq")
	proto.RegisterType((*SendRsp)(nil), "github.com.zchat.team.zim.api.rest.chat.SendRsp")
}

func init() { proto.RegisterFile("api/rest/chat/chat.proto", fileDescriptor_ac80e97576f6ff81) }

var fileDescriptor_ac80e97576f6ff81 = []byte{
	// 409 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xbd, 0x8b, 0x14, 0x31,
	0x1c, 0x9d, 0xcc, 0xde, 0xed, 0x47, 0x90, 0x2b, 0x82, 0x1c, 0xe3, 0x2a, 0xe1, 0x98, 0xc6, 0x43,
	0x98, 0x44, 0x4e, 0xb0, 0xb0, 0xd3, 0xce, 0xd2, 0xf1, 0x2a, 0x9b, 0x23, 0x37, 0x13, 0x72, 0x01,
	0xf3, 0xe1, 0x4c, 0x5c, 0xd8, 0xad, 0x5c, 0x2b, 0xc1, 0xc2, 0xaf, 0x46, 0x3b, 0xff, 0x03, 0x3b,
	0x6b, 0xcb, 0x2d, 0x17, 0x6c, 0x2c, 0x75, 0x47, 0x17, 0xfc, 0x2f, 0x24, 0xc9, 0x08, 0x8a, 0x8d,
	0xd7, 0xcc, 0xfc, 0xde, 0x7b, 0xbc, 0xc7, 0x4b, 0xf2, 0x83, 0x19, 0xb3, 0x92, 0x36, 0xbc, 0x75,
	0xb4, 0x3a, 0x63, 0xf1, 0x43, 0x6c, 0x63, 0x9c, 0x41, 0x57, 0x85, 0x74, 0x67, 0x8f, 0x4f, 0x49,
	0x65, 0x14, 0x59, 0x04, 0xde, 0x71, 0xa6, 0xc8, 0x42, 0x2a, 0xc2, 0xac, 0x24, 0xde, 0x43, 0x3c,
	0x3d, 0xbd, 0x22, 0x8c, 0x11, 0x0f, 0x39, 0xf5, 0x49, 0x4c, 0x6b, 0xe3, 0x98, 0x93, 0x46, 0xb7,
	0x31, 0x66, 0x7a, 0x51, 0x18, 0x61, 0xc2, 0x48, 0xfd, 0xd4, 0xb3, 0xf1, 0x57, 0x15, 0x82, 0xeb,
	0xc2, 0x58, 0xae, 0x99, 0x95, 0xb3, 0x23, 0x6a, 0x6c, 0x70, 0xfe, 0x9b, 0x92, 0x3f, 0x07, 0x70,
	0x74, 0x9f, 0xeb, 0xba, 0xe4, 0x8f, 0xd0, 0x65, 0x38, 0xa9, 0x8c, 0x9e, 0x9d, 0xb8, 0xb9, 0xe5,
	0x19, 0x38, 0x00, 0x87, 0xbb, 0xe5, 0xd8, 0x13, 0xc7, 0x73, 0xcb, 0xd1, 0x25, 0x38, 0x56, 0xad,
	0x88, 0x5a, 0x1a, 0xb4, 0x91, 0x6a, 0x45, 0x90, 0xf6, 0xe1, 0xb0, 0xe5, 0xba, 0xe6, 0x4d, 0x36,
	0x38, 0x00, 0x87, 0x93, 0xb2, 0x47, 0x9e, 0x77, 0xac, 0x11, 0xdc, 0x65, 0x3b, 0x91, 0x8f, 0x08,
	0x65, 0x70, 0x54, 0x19, 0xed, 0xb8, 0x76, 0xd9, 0x6e, 0x10, 0x7e, 0xc3, 0xfc, 0x66, 0x5f, 0xa6,
	0xb5, 0x68, 0x0f, 0xa6, 0xb2, 0x0e, 0x2d, 0x06, 0x65, 0x2a, 0x6b, 0x5f, 0xce, 0xc7, 0x9e, 0x38,
	0xa9, 0x62, 0x81, 0x41, 0x39, 0xf6, 0xc4, 0xb1, 0x54, 0xfc, 0xe8, 0x3d, 0x80, 0xe9, 0x5d, 0x85,
	0xde, 0x01, 0xb8, 0xe3, 0xfd, 0xe8, 0x3a, 0xf9, 0xcf, 0x3b, 0x26, 0xfd, 0xd9, 0xa7, 0xe7, 0x74,
	0xb4, 0x36, 0x2f, 0x5e, 0xdf, 0xde, 0x87, 0xc3, 0xed, 0xc7, 0x67, 0xdb, 0xe5, 0x07, 0x74, 0xe1,
	0xc7, 0x8b, 0x57, 0x3f, 0x9f, 0x2c, 0x23, 0x7a, 0xfa, 0xf9, 0xfb, 0x9b, 0x74, 0x2f, 0x9f, 0xd0,
	0x85, 0x54, 0xd4, 0x77, 0xbc, 0x05, 0xae, 0xdd, 0xb9, 0xb7, 0xfa, 0x86, 0x93, 0xd5, 0x06, 0x83,
	0xf5, 0x06, 0x83, 0xaf, 0x1b, 0x0c, 0x5e, 0x76, 0x38, 0x79, 0xdb, 0xe1, 0xe4, 0x53, 0x87, 0xc1,
	0xaa, 0xc3, 0x60, 0xdd, 0xe1, 0xe4, 0x4b, 0x87, 0x93, 0x07, 0x7f, 0xec, 0x07, 0x0d, 0x4d, 0x0a,
	0xdf, 0x24, 0x84, 0xfd, 0xb5, 0x53, 0xa7, 0xc3, 0xf0, 0x84, 0x37, 0x7e, 0x05, 0x00, 0x00, 0xff,
	0xff, 0x72, 0x75, 0x1b, 0xef, 0x6b, 0x02, 0x00, 0x00,
}

func (m *SendReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SendReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SendReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Content) > 0 {
		i -= len(m.Content)
		copy(dAtA[i:], m.Content)
		i = encodeVarintChat(dAtA, i, uint64(len(m.Content)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Target) > 0 {
		i -= len(m.Target)
		copy(dAtA[i:], m.Target)
		i = encodeVarintChat(dAtA, i, uint64(len(m.Target)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintChat(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0x1a
	}
	if m.MsgType != 0 {
		i = encodeVarintChat(dAtA, i, uint64(m.MsgType))
		i--
		dAtA[i] = 0x10
	}
	if m.ConvType != 0 {
		i = encodeVarintChat(dAtA, i, uint64(m.ConvType))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SendRsp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SendRsp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SendRsp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SendTime != 0 {
		i = encodeVarintChat(dAtA, i, uint64(m.SendTime))
		i--
		dAtA[i] = 0x10
	}
	if m.Id != 0 {
		i = encodeVarintChat(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintChat(dAtA []byte, offset int, v uint64) int {
	offset -= sovChat(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SendReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ConvType != 0 {
		n += 1 + sovChat(uint64(m.ConvType))
	}
	if m.MsgType != 0 {
		n += 1 + sovChat(uint64(m.MsgType))
	}
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovChat(uint64(l))
	}
	l = len(m.Target)
	if l > 0 {
		n += 1 + l + sovChat(uint64(l))
	}
	l = len(m.Content)
	if l > 0 {
		n += 1 + l + sovChat(uint64(l))
	}
	return n
}

func (m *SendRsp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovChat(uint64(m.Id))
	}
	if m.SendTime != 0 {
		n += 1 + sovChat(uint64(m.SendTime))
	}
	return n
}

func sovChat(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozChat(x uint64) (n int) {
	return sovChat(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SendReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowChat
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SendReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SendReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConvType", wireType)
			}
			m.ConvType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChat
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ConvType |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgType", wireType)
			}
			m.MsgType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChat
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MsgType |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChat
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChat
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChat
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Target", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChat
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChat
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChat
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Target = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Content", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChat
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChat
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChat
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Content = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipChat(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthChat
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SendRsp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowChat
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SendRsp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SendRsp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChat
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SendTime", wireType)
			}
			m.SendTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChat
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SendTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipChat(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthChat
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipChat(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowChat
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowChat
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowChat
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthChat
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupChat
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthChat
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthChat        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowChat          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupChat = fmt.Errorf("proto: unexpected end of group")
)
