// Code generated by protoc-gen-zmicro-gin. DO NOT EDIT.
// versions:
// - protoc-gen-zmicro-gin v0.1.0
// - protoc                v3.19.0
// source: api/rest/chat/chat.proto

package chat

import (
	context "context"
	errors "errors"
	gin "github.com/gin-gonic/gin"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = errors.New
var _ = context.TODO
var _ = gin.New

type ImHTTPServer interface {
	Send(context.Context, *SendReq, *SendRsp) error
	Validate(context.Context, any) error
	ErrorEncoder(c *gin.Context, err error, isBadRequest bool)
}

type UnimplementedImHTTPServer struct{}

func (*UnimplementedImHTTPServer) Send(context.Context, *SendReq, *SendRsp) error {
	return errors.New("method Send not implemented")
}
func (*UnimplementedImHTTPServer) Validate(context.Context, any) error { return nil }
func (*UnimplementedImHTTPServer) ErrorEncoder(c *gin.Context, err error, isBadRequest bool) {
	var code = 500
	if isBadRequest {
		code = 400
	}
	c.String(code, err.Error())
}

func RegisterImHTTPServer(g *gin.RouterGroup, srv ImHTTPServer) {
	r := g.Group("")
	r.POST("/zim/send", _Im_Send0_HTTP_Handler(srv))
}

func _Im_Send0_HTTP_Handler(srv ImHTTPServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		shouldBind := func(req any) error {
			if err := c.ShouldBind(req); err != nil {
				return err
			}
			return srv.Validate(c.Request.Context(), req)
		}

		var req SendReq
		var rsp SendRsp
		if err := shouldBind(&req); err != nil {
			srv.ErrorEncoder(c, err, true)
			return
		}
		err := srv.Send(c.Request.Context(), &req, &rsp)
		if err != nil {
			srv.ErrorEncoder(c, err, false)
			return
		}
		c.JSON(200, rsp)
	}
}
